import { Book } from './book';

export const BOOKS: Book[] = [
  { id: 1, title: 'Könyv1',
  authors: 'Szerző1', publisher: 'kiadó1',
  publish: 'kiadás1', category: 'DRAMA',
  price: 111, shortDesc: 'rövid le',
  longDesc: 'hosszú leírás',
   state: 'elérhető'},
   { id: 2, title: 'Könyv2',
   authors: 'Szerző1', publisher: 'kiadó1',
   publish: 'kiadás1', category: 'DRAMA',
   price: 222, shortDesc: 'rövid le',
   longDesc: 'hosszú leírás',
    state: 'elérhető' },
    { id: 333, title: 'Könyv3',
    authors: 'Szerző1', publisher: 'kiadó1',
    publish: 'kiadás1', category: 'DRAMA',
    price: 444, shortDesc: 'rövid le',
    longDesc: 'hosszú leírás',
     state: 'elérhető' },
     { id: 4, title: 'Könyv4',
     authors: 'Szerző1', publisher: 'kiadó1',
     publish: 'kiadás1', category: 'HOBBY',
     price: 555, shortDesc: 'rövid le',
     longDesc: 'hosszú leírás',
      state: 'elérhető' },
      { id: 5, title: 'Könyv5',
      authors: 'Szerző1', publisher: 'kiadó1',
      publish: 'kiadás1', category: 'COMEDY',
      price: 666, shortDesc: 'rövid le',
      longDesc: 'hosszú leírás',
       state: 'elérhető'},
  { id: 6, title: 'Könyv6',
       authors: 'Szerző1', publisher: 'kiadó1',
       publish: 'kiadás1', category: 'HOBBY',
       price: 777, shortDesc: 'rövid le',
       longDesc: 'hosszú leírás',
        state: 'elérhető' }
];
