INSERT INTO USER (ID, NAME, ADDRESS, USERNAME, PASSWORD, EMAIL, ROLE) VALUES (1, 'PISTIKE', 'BUDAPEST', 'ASDF123','pw1', 'MAIL1@MAIL.COM', 'ADMIN');
INSERT INTO USER (ID, NAME, ADDRESS, USERNAME, PASSWORD, EMAIL, ROLE) VALUES (2, 'KLÁRIKA', 'BUDAPEST', 'ASDF123', 'pw2', 'MAIL2@MAIL.COM', 'GUEST');
INSERT INTO USER (ID, NAME, ADDRESS, USERNAME, PASSWORD, EMAIL, ROLE) VALUES (3, 'JÓSKA', 'BUDAPEST', 'ASDF123', 'pw3', 'MAIL3@MAIL.COM', 'USER');

